spring.application.name=SGA
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/sga_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
